version: '3'
services: 
  kwetter_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kwetter
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - kwetter
  kwetter_backend:
    image: abevers/kwetter-backend:latest
    environment: 
      - JDBC_NAME=kwetter
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_NAME=kwetter
      - DATABASE_PORT=3306
      - DATABASE_HOST=kwetter_db
    ports: 
      - 8080:8080
      - 4848:4848
      - 8181:8181
      - 9009:9009
    volumes:
      - kwetter_payara_artifact:/opt/payara/deployments
    networks:
      - kwetter
  kwetter_websockets:
    image: abevers/kwetter-websockets:latest
    ports:
      - 3001:3001
    networks:
      - kwetter
  kwetter_frontend:
    image: abevers/kwetter-frontend:latest
    ports:
      - 4200:4200
    networks:
      - kwetter
volumes:
  kwetter_payara_artifact:
networks:
  kwetter:
      driver: bridge
