version: '3'
services: 
  kwetter_db:
    image: mysql
    container_name: kwetter_db
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kwetter
    volumes:
      - ./database:/var/lib/mysql
  kwetter_backend:
    build: kwetter-backend
    container_name: kwetter_backend
    environment: 
      - JDBC_NAME=kwetter
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_NAME=kwetter
      - DATABASE_PORT=3306
      - DATABASE_HOST=kwetter_db
    ports: 
      - 8080:8080
      - 4848:4848
      - 8181:8181
      - 9009:9009
    volumes:
      - ./artifact:/opt/payara/deployments
    links:
      - "kwetter_db:kwetter_db"
    depends_on:
      - kwetter_db
  kwetter_websockets:
    build: kwetter-websockets
    container_name: kwetter_websockets
    ports:
      - 3001:3001
  kwetter_frontend:
    build: kwetter-frontend
    container_name: kwetter_frontend
    ports:
      - 4200:4200
    links:
     - "kwetter_backend:kwetter_backend"
     - "kwetter_websockets:kwetter_websockets"
    depends_on:
      - kwetter_backend
      - kwetter_websockets
